/* Generated By:JavaCC: Do not edit this line. NodePathParserConstants.java */
package org.plcore.userio.path.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface NodePathParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int HYPHEN = 1;
  /** RegularExpression Id. */
  int SEPARATOR = 2;
  /** RegularExpression Id. */
  int WILDCARD = 3;
  /** RegularExpression Id. */
  int WILDCARDX2 = 4;
  /** RegularExpression Id. */
  int NUMBER = 5;
  /** RegularExpression Id. */
  int DIGIT = 6;
  /** RegularExpression Id. */
  int LETTER = 7;
  /** RegularExpression Id. */
  int NAME = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"-\"",
    "\"/\"",
    "\"*\"",
    "\"**\"",
    "<NUMBER>",
    "<DIGIT>",
    "<LETTER>",
    "<NAME>",
  };

}
